server:
  port: 8080

spring:
  application:
    name: tts
    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tts?serverTimezone=Asia/Seoul
    username: postgres
    password: 1234

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher
      
mybatis:
  mapper-locations: classpath:mapper/*.xml
  
  configuration:
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true
    default-executor-type: REUSE
    use-generated-keys: true